volumes:
  mssql_data:
  

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    hostname: mssql
    environment:
      MSSQL_SA_PASSWORD: "1G69YN3xOErR"
      ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"
    volumes:
    - mssql_data:/var/opt/mssql
