name: Inventory Management System

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        name: Build application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5
              with:
                fetch-depth: 0
                clean: true

            - name: Install .NET Core SDK
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '9.x.x'

            - name: Restore project's dependencies
              run: dotnet restore ${{ github.workspace }} --no-cache

            - name: Build project
              run: dotnet build ${{ github.workspace }} --no-restore -c Release

            - name: Check file structure
              run: ls -la ${{ github.workspace }} | find obj
              # run: ls -la ${{ github.workspace }}/obj/Release/net9.0

            - name: Publish project
              run: dotnet publish ${{ github.workspace }} --no-build --output ${{ github.workspace }}/.out

