name: Workflow chaining

on:
  workflow_dispatch:
    inputs:
      runJob3:
        type: boolean
        description: Run Job 3?
        required: true

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
    - name: Say hello
      run: echo "Hello from Job 1 ^^"

  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs:
    - job1
    steps:
    - name: Say hello
      run: echo "Hello from Job 2 -_-"
    - name: Meet error
      run: echo "Meet error ❌" && exit 1

  job3:
    name: Job 3
    runs-on: ubuntu-latest
    if: github.event.inputs.runJob3 == 'true'
    needs:
    - job1
    steps:
    - name: Say hello
      run: echo "Hello from Job 3 :P"

  job4:
    name: Job 4
    runs-on: ubuntu-latest
    # if: always()
    needs:
    - job2
    - job3
    steps:
    - name: Say hello
      run: echo "Hello from Job 4 ^o^"
  
